
ALTER TABLE public.admin_notifications ADD CONSTRAINT admin_notifications_pkey PRIMARY KEY (id);
ALTER TABLE public.ai_generations ADD CONSTRAINT ai_generations_pkey PRIMARY KEY (id);
ALTER TABLE public.balance_events ADD CONSTRAINT balance_events_pkey PRIMARY KEY (id);
ALTER TABLE public.blog_posts ADD CONSTRAINT blog_posts_pkey PRIMARY KEY (id);
ALTER TABLE public.global_topic_resources ADD CONSTRAINT global_topic_resources_pkey PRIMARY KEY (id);
ALTER TABLE public.global_topics ADD CONSTRAINT global_topics_pkey PRIMARY KEY (id);
ALTER TABLE public.groups ADD CONSTRAINT groups_pkey PRIMARY KEY (id);
ALTER TABLE public.homework_submissions ADD CONSTRAINT homework_submissions_pkey PRIMARY KEY (id);
ALTER TABLE public.lesson_instances ADD CONSTRAINT lesson_instances_pkey PRIMARY KEY (id);
ALTER TABLE public.lesson_reminder_log ADD CONSTRAINT lesson_reminder_log_pkey PRIMARY KEY (id);
ALTER TABLE public.notifications ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);
ALTER TABLE public.payment_history ADD CONSTRAINT payment_history_pkey PRIMARY KEY (id);
ALTER TABLE public.playground_credits ADD CONSTRAINT playground_credits_pkey PRIMARY KEY (user_id);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.push_tokens ADD CONSTRAINT push_tokens_pkey PRIMARY KEY (id);
ALTER TABLE public.resources ADD CONSTRAINT resources_pkey PRIMARY KEY (id);
ALTER TABLE public.student_lesson_tracking ADD CONSTRAINT student_lesson_tracking_pkey PRIMARY KEY (id);
ALTER TABLE public.student_lessons ADD CONSTRAINT student_lessons_pkey PRIMARY KEY (id);
ALTER TABLE public.student_resource_completion ADD CONSTRAINT student_resource_completion_pkey PRIMARY KEY (id);
ALTER TABLE public.students ADD CONSTRAINT students_pkey PRIMARY KEY (id);
ALTER TABLE public.teacher_balance ADD CONSTRAINT teacher_balance_pkey PRIMARY KEY (id);
ALTER TABLE public.topics ADD CONSTRAINT topics_pkey PRIMARY KEY (id);
ALTER TABLE public.trial_lessons ADD CONSTRAINT trial_lessons_pkey PRIMARY KEY (id);
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_pkey PRIMARY KEY (id);
ALTER TABLE public.blog_posts ADD CONSTRAINT blog_posts_slug_key UNIQUE (slug);
ALTER TABLE public.lesson_instances ADD CONSTRAINT lesson_instances_student_teacher_cycle_lesson_number_key UNIQUE (student_id, teacher_id, package_cycle, lesson_number);
ALTER TABLE public.lesson_reminder_log ADD CONSTRAINT lesson_reminder_log_recipient_user_id_lesson_key_lesson_dat_key UNIQUE (recipient_user_id, lesson_key, lesson_date, reminder_type);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_user_id_key UNIQUE (user_id);
ALTER TABLE public.push_tokens ADD CONSTRAINT push_tokens_token_key UNIQUE (token);
ALTER TABLE public.student_lesson_tracking ADD CONSTRAINT unique_student_teacher_tracking UNIQUE (student_id, teacher_id);
ALTER TABLE public.student_lessons ADD CONSTRAINT unique_student_lesson_time UNIQUE (student_id, day_of_week, start_time);
ALTER TABLE public.student_resource_completion ADD CONSTRAINT student_resource_completion_student_id_resource_id_key UNIQUE (student_id, resource_id);
ALTER TABLE public.students ADD CONSTRAINT students_teacher_id_student_id_key UNIQUE (teacher_id, student_id);
ALTER TABLE public.teacher_balance ADD CONSTRAINT teacher_balance_teacher_id_key UNIQUE (teacher_id);
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_user_id_role_key UNIQUE (user_id, role);
ALTER TABLE public.ai_generations ADD CONSTRAINT ai_generations_modality_check CHECK ((modality = ANY (ARRAY['text'::text, 'image'::text, 'video'::text])));
ALTER TABLE public.ai_generations ADD CONSTRAINT ai_generations_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text])));
ALTER TABLE public.balance_events ADD CONSTRAINT balance_events_event_type_check CHECK ((event_type = ANY (ARRAY['lesson_complete'::text, 'lesson_undo'::text, 'trial_complete'::text, 'trial_undo'::text, 'manual_adjust'::text, 'balance_reset'::text, 'data_repair'::text])));
ALTER TABLE public.push_tokens ADD CONSTRAINT push_tokens_platform_check CHECK ((platform = ANY (ARRAY['android'::text, 'ios'::text, 'web'::text])));
ALTER TABLE public.push_tokens ADD CONSTRAINT push_tokens_role_check CHECK ((role = ANY (ARRAY['teacher'::text, 'student'::text, 'admin'::text])));
ALTER TABLE public.trial_lessons ADD CONSTRAINT trial_lessons_day_of_week_check CHECK (((day_of_week >= 0) AND (day_of_week <= 6)));
ALTER TABLE public.ai_generations ADD CONSTRAINT ai_generations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
ALTER TABLE public.global_topic_resources ADD CONSTRAINT global_topic_resources_global_topic_id_fkey FOREIGN KEY (global_topic_id) REFERENCES global_topics(id);
ALTER TABLE public.global_topics ADD CONSTRAINT global_topics_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.groups ADD CONSTRAINT groups_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES profiles(user_id);
ALTER TABLE public.lesson_instances ADD CONSTRAINT lesson_instances_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE SET NULL;
ALTER TABLE public.notifications ADD CONSTRAINT notifications_homework_id_fkey FOREIGN KEY (homework_id) REFERENCES homework_submissions(id) ON DELETE CASCADE;
ALTER TABLE public.payment_history ADD CONSTRAINT payment_history_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.playground_credits ADD CONSTRAINT playground_credits_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.push_tokens ADD CONSTRAINT push_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.resources ADD CONSTRAINT resources_topic_id_fkey FOREIGN KEY (topic_id) REFERENCES topics(id);
ALTER TABLE public.students ADD CONSTRAINT students_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE SET NULL;
ALTER TABLE public.students ADD CONSTRAINT students_student_id_fkey FOREIGN KEY (student_id) REFERENCES profiles(user_id);
ALTER TABLE public.students ADD CONSTRAINT students_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES profiles(user_id);
ALTER TABLE public.teacher_balance ADD CONSTRAINT teacher_balance_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.topics ADD CONSTRAINT topics_student_id_fkey FOREIGN KEY (student_id) REFERENCES profiles(user_id);
ALTER TABLE public.topics ADD CONSTRAINT topics_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES profiles(user_id);
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
;
