
CREATE INDEX idx_admin_notifications_push_unprocessed ON public.admin_notifications USING btree (id) WHERE ((push_sent_at IS NULL) AND (push_processing_at IS NULL));
CREATE INDEX idx_balance_events_teacher_id ON public.balance_events USING btree (teacher_id);
CREATE INDEX idx_gtr_topic ON public.global_topic_resources USING btree (global_topic_id);
CREATE INDEX idx_global_topics_teacher_id ON public.global_topics USING btree (teacher_id);
CREATE INDEX idx_groups_teacher_id ON public.groups USING btree (teacher_id);
CREATE INDEX idx_homework_submissions_batch_id ON public.homework_submissions USING btree (batch_id);
CREATE INDEX idx_homework_submissions_student_teacher ON public.homework_submissions USING btree (student_id, teacher_id, created_at DESC);
CREATE INDEX idx_lesson_instances_group_id ON public.lesson_instances USING btree (group_id);
CREATE INDEX idx_lesson_instances_package_cycle ON public.lesson_instances USING btree (package_cycle);
CREATE INDEX idx_lesson_instances_student ON public.lesson_instances USING btree (student_id, teacher_id, status);
CREATE INDEX idx_lesson_instances_student_teacher_cycle ON public.lesson_instances USING btree (student_id, teacher_id, package_cycle);
CREATE INDEX idx_lesson_instances_teacher_date ON public.lesson_instances USING btree (teacher_id, lesson_date, start_time, end_time);
CREATE INDEX idx_lesson_instances_teacher_status_date ON public.lesson_instances USING btree (teacher_id, status, lesson_date);
CREATE UNIQUE INDEX uniq_active_planned_slot ON public.lesson_instances USING btree (student_id, lesson_date, start_time) WHERE (status = 'planned'::text);
CREATE INDEX idx_notifications_created_at ON public.notifications USING btree (created_at DESC);
CREATE INDEX idx_notifications_is_read ON public.notifications USING btree (is_read);
CREATE INDEX idx_notifications_push_unprocessed ON public.notifications USING btree (id) WHERE ((push_sent_at IS NULL) AND (push_processing_at IS NULL));
CREATE INDEX idx_notifications_teacher_id ON public.notifications USING btree (teacher_id);
CREATE INDEX idx_payment_history_payment_date ON public.payment_history USING btree (payment_date DESC);
CREATE INDEX idx_payment_history_teacher_id ON public.payment_history USING btree (teacher_id);
CREATE INDEX idx_resources_topic ON public.resources USING btree (topic_id);
CREATE INDEX idx_student_lessons_student_id ON public.student_lessons USING btree (student_id);
CREATE INDEX idx_student_lessons_teacher_id ON public.student_lessons USING btree (teacher_id);
CREATE INDEX idx_student_lessons_week ON public.student_lessons USING btree (week_start_date);
CREATE INDEX idx_src_student_resource ON public.student_resource_completion USING btree (student_id, resource_id, is_completed);
CREATE INDEX idx_students_group_id ON public.students USING btree (group_id);
CREATE INDEX idx_students_is_archived ON public.students USING btree (is_archived);
CREATE INDEX idx_students_student_teacher ON public.students USING btree (student_id, teacher_id);
CREATE INDEX idx_trial_lessons_date ON public.trial_lessons USING btree (lesson_date);
CREATE INDEX idx_trial_lessons_teacher_date ON public.trial_lessons USING btree (teacher_id, lesson_date);
;
